#!/usr/bin/env python
'''
Plot a log file generated by A.Roy's GPIB Counter program that logs maser 1PPS vs GPS 1PPS over time.

Usage: plotMaserGPSlog.py <logfile>
'''
import sys
import datetime
import matplotlib.pyplot as plt
import numpy

'''Convert dates like '2018.108.17:53:19.00' into Python datetime'''
def logtime_format_to_datetime(tlog):
	return datetime.datetime.strptime(tlog, '%Y.%j.%H:%M:%S.%f')

if len(sys.argv) != 2:
	print(__doc__)
	sys.exit(1)

f = open(sys.argv[1], 'r')
logdata = f.readlines()
logdata = logdata[1:] # remove the header row "2012.001.12:00:00.00"pollCounters 1.04 in FieldSystem format"

times=[]
offsets=[]
T0 = None

for line in logdata:
	# 2018.108.17:53:19.00/gps-maser/5.322221557e-01
	elems = line.split('/')
	if len(elems) < 3:
		continue
	if float(elems[2]) == 0.0:
		continue
	T = logtime_format_to_datetime(elems[0])
	if T0==None:
		T0 = T
	times.append((T-T0).total_seconds())
	offsets.append(float(elems[2]))

times = numpy.asarray(times)
offsets = numpy.asarray(offsets)

med = numpy.median(offsets)
stddev = numpy.std(offsets)
t0 = numpy.min(times)
t1 = numpy.max(times)

offsets = offsets - med
plt.plot(times, offsets, 'kx:')
plt.xlabel('Seconds since %s' % (T0))
plt.ylabel('Time delta of 1PPS signals in seconds')
plt.axis([t0, t1, -3*stddev, 3*stddev])
plt.draw()
plt.show()
while True:
	pass

