INST_PATH=/etc/r2dbe/

all:

install:
	mkdir -p $(INST_PATH)
	cp -a APEX_r2dbe1_setup.sh APEX_r2dbe2_setup.sh R2DBE_config.py $(INST_PATH)
	cp -a alc.py r2dbe_start.py eht-r2dbe-1.cfg eht-r2dbe-2.cfg $(INST_PATH)
	cp -a quickspecR2DBE.py requantizeR2DBE.py timing_query.py $(INST_PATH)
