###############################################################################
# Telegraf config: Rec Room Temperatute via LAN Temperature Sensor
###############################################################################

[[inputs.http]]
name_override = "ip_tsensor1"

# IP Thermoneter by ipthermometer.eu
# Behind ctrlsw12 port #11:
#   urls = [ "http://192.168.0.100/t" ]
# After Kevin gave us a dedicated internal static IP,
# and vlan tagging port #11 over to the house network:
urls = [ "http://10.0.2.230/t" ]

method = "GET"
timeout = "5s"
interval = "20s"
data_format = "value"
data_type = "float"

[[outputs.influxdb_v2]]
urls = ["http://localhost:8086"]
token = "16GPmHAXsutcsNbZQZ9ON541gfMKMEVd2KU9Kezw6TdTHyc2ZWkAEuhY8CJUUlcW-3M_P28VzJDOspp0Ofdg8A=="
organization = "APEX"
bucket = "eht"
