###############################################################################
# Telegraf config: Rec Room Temperatute via LAN Temperature Sensor
###############################################################################

[[inputs.http]]
name_override = "ip_tsensor1"
urls = [ "http://192.168.0.100/t" ]
method = "GET"
timeout = "5s"
interval = "20s"
data_format = "value"
data_type = "float"

[[outputs.influxdb_v2]]
urls = ["http://localhost:8086"]
token = "16GPmHAXsutcsNbZQZ9ON541gfMKMEVd2KU9Kezw6TdTHyc2ZWkAEuhY8CJUUlcW-3M_P28VzJDOspp0Ofdg8A=="
organization = "APEX"
bucket = "eht"
