# 
#
# makefile for test, okt 2008, zei
FFLAGS = -c
#
LIBES= /usr2/fs/clib/clib.a /usr2/fs/rtelb/rtelb.a /usr2/fs/port/port.a\
/usr2/fs/poclb/poclb.a\
/usr2/fs/fslb/fslb.a /usr2/fs/lnfch/lnfch.a /usr2/fs/flib/flib.a\
/usr2/fs/fclib/fclib.a  /usr/lib/libm.a

OBJECTS = server4.o 
           
#
server4:	 $(OBJECTS)
#
	gcc  -o  server4  server4.o  
 
#
